spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
openai:
  model: gpt-3.5-turbo
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # Spring MVC 관련 디버깅 로그
    com.jobprep.resume_feedback: DEBUG  # 패키지 경로에 따른 디버깅 로그
  file:
    name: logs/spring-boot-application.log  # 로그 파일