spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB # 하나의 파일 크기 제한 (10MB)
      max-request-size: 10MB # 요청 전체 크기 제한 (10MB)
  ai.openai:
    api-key: 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
    url: https://api.openai.com/v1/chat/completions
    model: gpt-3.5-turbo
  threads.virtual.enabled: true


logging:
  level:
    org.apache.hc: DEBUG
    org.springframework.web: DEBUG
tessdata:
  prefix: classpath:tessdata
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024
